title: Aventures Sonores
description: > # this means to ignore newlines until "show_excerpts:"
 We are AVENTURES SONORES, a creative collective group that blends art and technology to make physical and digital (phygital) experiential adventures. We strongly believe that listening is not only a way to receive and decode information, but mediates all of our relationships: with others, with the environment, with society in general, and even with ourselves.
# baseurl: "/"
url: "aventures-sonores.github.io" # change this URL, this is needed for generating right sitemap

permalink: "/blog/:title/"

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-soopr-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

css_dir: "/" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title"
  pages:
    output: true
    permalink: "/:title"

jekyll-minifier:
  uglifier_args:
    harmony: true

# soopr:
  # publish_token: "pt_618ffa16a451d0066a9220b278201d19" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

twitter:
  card: summary_large_image

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
